name: Acquire Unity Activation File (.alf)

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  activation:
    name: Request Activation File (.alf)
    runs-on: macos-13
    steps:
      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v2

      - name: Upload .alf artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_Activation_File
          path: "**/*.alf"
