name: Acquire Unity Activation File (.alf)

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request Activation File (.alf)
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2021.1.11f1-base-1
    steps:
      - name: Generate manual activation file
        run: |
          unity-editor -batchmode -nographics -createManualActivationFile -logfile /dev/stdout || true
          ls -la

      - name: Upload .alf artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_Activation_File
          path: "**/*.alf"
