name: Build iOS IPA

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  packageIPA:
    name: Build & Package RogueTower.ipa
    runs-on: macos-14
    steps:
      - name: Checkout repository (with Git LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build Xcode Archive & Package IPA
        run: |
          cd Build
          # Build app into ./output directory using Xcode
          xcodebuild build -project Unity-iPhone.xcodeproj -scheme Unity-iPhone -destination 'generic/platform=iOS' -configuration Release -derivedDataPath output CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          # Package .app into .ipa
          mkdir -p Payload
          cp -r output/Build/Products/Release-iphoneos/*.app Payload/
          zip -r RogueTower.ipa Payload
          mv RogueTower.ipa ../

      - name: Upload RogueTower.ipa
        uses: actions/upload-artifact@v4
        with:
          name: RogueTower-iOS-IPA
          path: RogueTower.ipa
